# Generated by Django 5.2.14 on 2026-05-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_review_summary_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review_summary',
        ),
        migrations.AddField(
            model_name='product',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='satisfaction_by_type',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
