# Generated by Django 5.2.14 on 2026-05-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_review_summary_product_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recommend_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
