# Generated by Django 5.2.14 on 2026-06-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review_recommend_count_review_review_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='oliveyoung_url',
            field=models.URLField(max_length=500),
        ),
    ]
