# Generated by Django 5.2.14 on 2026-06-23 04:15

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image_url_alter_product_oliveyoung_url'),
    ]

    operations = [
        # vector 컬럼을 만들기 전에 PostgreSQL에 pgvector 확장을 먼저 생성한다.
        # (CREATE EXTENSION IF NOT EXISTS vector)
        VectorExtension(),
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
