# Generated by Django 5.2.14 on 2026-06-24 01:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='form',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('toner', '스킨/토너'), ('lotion', '로션/에멀전'), ('essence', '에센스'), ('serum', '세럼/앰플'), ('cream', '크림'), ('mist', '미스트'), ('suncream', '선크림'), ('cleanser', '클렌저'), ('pad', '패드'), ('mask', '마스크/팩')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
