# Generated by Django 5.2.14 on 2026-06-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('products', '0007_product_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='product',
        ),
        migrations.AddField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts', to='products.product'),
        ),
    ]
